aal_msgs/AdaptationOptions[] adaptation_space
float64[] utility_previous
float64[] safeties
float64[] powers
float64[] moves
string task_identifier
string adaptation_strategy
---
bool success
aal_msgs/Adaptation[] applied_adaptations
