aal_msgs/AdaptationOptions[] adaptation_space
float64[] utility_previous
rebet_msgs/QR[] qrs
diagnostic_msgs/KeyValue[] context
diagnostic_msgs/KeyValue[] config
string task_identifier
string adaptation_strategy
---
bool success
aal_msgs/Adaptation[] applied_adaptations
